// Micro:bit Challenges - Updated 2026
// Basado en el currículo oficial de Microbit Projects (Make It Code It)

export const MICROBIT_CHALLENGES = {
  beginner: [
    { numero: 1, id: "heart", titulo: "Corazón", dificultad: "Principiante" },
    { numero: 2, id: "beating-heart", titulo: "Corazón palpitante", dificultad: "Principiante" },
    { numero: 3, id: "animated-animals", titulo: "Animales animados", dificultad: "Principiante" },
    { numero: 4, id: "emotion-badge", titulo: "Insignia de emociones", dificultad: "Principiante" },
    { numero: 5, id: "get-silly", titulo: "Haz el tonto", dificultad: "Principiante" },
    { numero: 6, id: "flashing-emotions", titulo: "Emociones intermitentes", dificultad: "Principiante" },
    { numero: 7, id: "here-comes-the-sun", titulo: "Aquí llega el sol", dificultad: "Principiante" },
    { numero: 8, id: "shining-sunbeams", titulo: "Rayos de sol brillantes", dificultad: "Principiante" },
    { numero: 9, id: "sunlight-sensor", titulo: "Sensor de luz solar", dificultad: "Principiante" },
    { numero: 10, id: "name-badge", titulo: "Insignia de nombre", dificultad: "Principiante" },
    { numero: 11, id: "dice", titulo: "Dados", dificultad: "Principiante" },
    { numero: 12, id: "magic-8-ball", titulo: "Bola 8 mágica", dificultad: "Principiante" },
    { numero: 13, id: "rock-paper-scissors", titulo: "Piedra, papel o tijera", dificultad: "Principiante" },
    { numero: 14, id: "graphical-dice", titulo: "Dados gráficos", dificultad: "Principiante" },
    { numero: 15, id: "step-counter", titulo: "Contador de pasos", dificultad: "Principiante" },
    { numero: 16, id: "low-energy-step-counter", titulo: "Contador de pasos (Bajo consumo)", dificultad: "Principiante" },
    { numero: 17, id: "scratch-jumping-cat", titulo: "Scratch: Gato saltarín", dificultad: "Principiante" },
    { numero: 18, id: "scratch-theremin", titulo: "Scratch: Theremin", dificultad: "Principiante" },
    { numero: 19, id: "scratch-boom-box", titulo: "Scratch: Boom-box", dificultad: "Principiante" },
    { numero: 20, id: "scratch-hungry-dino", titulo: "Scratch: Dinosaurio hambriento", dificultad: "Principiante" },
    { numero: 21, id: "scratch-paint", titulo: "Scratch: Pintura", dificultad: "Principiante" },
    { numero: 22, id: "scratch-guitar", titulo: "Scratch: Guitarra", dificultad: "Principiante" },
    { numero: 23, id: "compass-bearing", titulo: "Rumbo de brújula", dificultad: "Principiante" },
    { numero: 24, id: "thermometer", titulo: "Termómetro", dificultad: "Principiante" },
    { numero: 25, id: "light-alarm", titulo: "Alarma de luz", dificultad: "Principiante" },
    { numero: 26, id: "clap-heart", titulo: "Corazón con aplauso", dificultad: "Principiante" },
    { numero: 27, id: "sunbeam", titulo: "Rayo de sol", dificultad: "Principiante" },
    { numero: 28, id: "nightlight", titulo: "Luz nocturna", dificultad: "Principiante" },
    { numero: 29, id: "counter", titulo: "Contador", dificultad: "Principiante" },
    { numero: 30, id: "activity-picker", titulo: "Selector de actividades", dificultad: "Principiante" },
    { numero: 31, id: "simple-tilt-alarm", titulo: "Alarma de inclinación simple", dificultad: "Principiante" },
    { numero: 32, id: "calming-leds", titulo: "LEDs relajantes", dificultad: "Principiante" },
    { numero: 33, id: "saving-sea-turtles", titulo: "Salvando tortugas marinas", dificultad: "Principiante" },
    { numero: 34, id: "light-up-fishing-nets", titulo: "Redes de pesca luminosas", dificultad: "Principiante" },
    { numero: 35, id: "tracking-polar-bears", titulo: "Rastreo de osos polares", dificultad: "Principiante" },
    { numero: 36, id: "animal-tracker", titulo: "Rastreador de animales", dificultad: "Principiante" },
    { numero: 37, id: "temperature-data-logger", titulo: "Registrador de temperatura", dificultad: "Principiante" },
    { numero: 38, id: "led-data-logger", titulo: "Registrador de datos LED", dificultad: "Principiante" },
    { numero: 39, id: "clap-hearts", titulo: "Corazones con aplauso", dificultad: "Principiante" },
    { numero: 40, id: "disco lights", titulo: "Luces de discoteca", dificultad: "Principiante" },
    { numero: 41, id: "sound-meter", titulo: "Medidor de sonido", dificultad: "Principiante" },
    { numero: 42, id: "touch-heart", titulo: "Corazón táctil", dificultad: "Principiante" },
    { numero: 43, id: "sound-emotion-badge", titulo: "Insignia de emoción por sonido", dificultad: "Principiante" },
    { numero: 44, id: "sensory-toy", titulo: "Juguete sensorial", dificultad: "Principiante" },
    { numero: 45, id: "constant-light-experiment", titulo: "Experimento luz constante", dificultad: "Principiante" },
    { numero: 46, id: "sunlight-experiment", titulo: "Experimento luz solar", dificultad: "Principiante" },
    { numero: 47, id: "salt-water-experiment", titulo: "Experimento agua salada", dificultad: "Principiante" },
    { numero: 48, id: "solar-energy-experiment", titulo: "Experimento energía solar", dificultad: "Principiante" },
    { numero: 49, id: "heart-rate-experiment", titulo: "Experimento ritmo cardíaco", dificultad: "Principiante" },
    { numero: 50, id: "reaction-time-experiment", titulo: "Experimento tiempo reacción", dificultad: "Principiante" },
    { numero: 51, id: "species-counter", titulo: "Contador de especies", dificultad: "Principiante" },
    { numero: 52, id: "water-bottle-alert", titulo: "Alerta de botella de agua", dificultad: "Principiante" },
    { numero: 53, id: "cookie-tin-alarm", titulo: "Alarma de caja de galletas", dificultad: "Principiante" },
    { numero: 54, id: "get-up", titulo: "¡Levántate!", dificultad: "Principiante" },
    { numero: 55, id: "times-tables-tester", titulo: "Probador de tablas de multiplicar", dificultad: "Principiante" },
    { numero: 56, id: "meet-your-microbit", titulo: "Conoce tu micro:bit", dificultad: "Principiante" },
    { numero: 57, id: "festive-decoration", titulo: "Decoración festiva", dificultad: "Principiante" }
  ],
  intermediate: [
    { numero: 1, id: "sensitive-step-counter", titulo: "Contador de pasos sensible", dificultad: "Intermedio" },
    { numero: 2, id: "compass-north", titulo: "Brújula Norte", dificultad: "Intermedio" },
    { numero: 3, id: "max-min-thermometer", titulo: "Termómetro Máx-Mín", dificultad: "Intermedio" },
    { numero: 4, id: "make-some-noise", titulo: "Hagamos ruido", dificultad: "Intermedio" },
    { numero: 5, id: "frere-jacques-loops", titulo: "Bucles de Frère Jacques", dificultad: "Intermedio" },
    { numero: 6, id: "group-teleporting-duck", titulo: "Pato teletransportador grupal", dificultad: "Intermedio" },
    { numero: 7, id: "tell-me-a-secret", titulo: "Cuéntame un secreto", dificultad: "Intermedio" },
    { numero: 8, id: "indoor-outdoor-thermometer", titulo: "Termómetro Interior-Exterior", dificultad: "Intermedio" },
    { numero: 9, id: "heartbeat-beacon", titulo: "Baliza de latido", dificultad: "Intermedio" },
    { numero: 10, id: "treasure-hunt", titulo: "Búsqueda del tesoro", dificultad: "Intermedio" },
    { numero: 11, id: "activity-array", titulo: "Matriz de actividades", dificultad: "Intermedio" },
    { numero: 12, id: "fahrenheit-thermometer", titulo: "Termómetro Fahrenheit", dificultad: "Intermedio" },
    { numero: 13, id: "jukebox-with-volume", titulo: "Jukebox con volumen", dificultad: "Intermedio" },
    { numero: 14, id: "simple-door-alarm", titulo: "Alarma de puerta simple", dificultad: "Intermedio" },
    { numero: 15, id: "touch-timer", titulo: "Temporizador táctil", dificultad: "Intermedio" },
    { numero: 16, id: "touch-stopwatch", titulo: "Cronómetro táctil", dificultad: "Intermedio" },
    { numero: 17, id: "sound-logger", titulo: "Registrador de sonido", dificultad: "Intermedio" },
    { numero: 18, id: "microbit-pet", titulo: "Mascota micro:bit", dificultad: "Intermedio" },
    { numero: 19, id: "spirit-level", titulo: "Nivel de burbuja", dificultad: "Intermedio" },
    { numero: 20, id: "sound-compass", titulo: "Brújula de sonido", dificultad: "Intermedio" },
    { numero: 21, id: "candle", titulo: "Vela", dificultad: "Intermedio" },
    { numero: 22, id: "clap-o-meter", titulo: "Aplausómetro", dificultad: "Intermedio" },
    { numero: 23, id: "traffic-survey-data-logger", titulo: "Encuesta de tráfico", dificultad: "Intermedio" },
    { numero: 24, id: "environment-data-logger", titulo: "Registrador ambiental", dificultad: "Intermedio" },
    { numero: 25, id: "movement-data-logger", titulo: "Registrador de movimiento", dificultad: "Intermedio" },
    { numero: 26, id: "conductivity-tester", titulo: "Probador de conductividad", dificultad: "Intermedio" },
    { numero: 27, id: "sound-insulation-meter", titulo: "Aislamiento acústico", dificultad: "Intermedio" },
    { numero: 28, id: "kick-strength-data-logger", titulo: "Fuerza de patada", dificultad: "Intermedio" },
    { numero: 29, id: "funny-voice-recorder", titulo: "Grabadora de voces", dificultad: "Intermedio" },
    { numero: 30, id: "secure-messaging", titulo: "Mensajería segura", dificultad: "Intermedio" },
    { numero: 31, id: "hot-potato-game", titulo: "Patata caliente", dificultad: "Intermedio" },
    { numero: 32, id: "hot-and-cold-game", titulo: "Caliente y frío", dificultad: "Intermedio" },
    { numero: 33, id: "distance-calculator", titulo: "Calculadora de distancia", dificultad: "Intermedio" },
    { numero: 34, id: "poetry-generator", titulo: "Generador de poesía", dificultad: "Intermedio" },
    { numero: 35, id: "odd-and-even-numbers", titulo: "Pares e impares", dificultad: "Intermedio" },
    { numero: 36, id: "simple-ai-exercise-timer", titulo: "Temporizador IA simple", dificultad: "Intermedio" },
    { numero: 37, id: "halloween-project", titulo: "Proyecto Halloween", dificultad: "Intermedio" },
    { numero: 38, id: "ai-activity-timer", titulo: "Temporizador de actividad IA", dificultad: "Intermedio" },
    { numero: 39, id: "ai-storytelling-friend", titulo: "Amigo contador de historias IA", dificultad: "Intermedio" },
    { numero: 40, id: "evaporation-experiment", titulo: "Experimento de evaporación", dificultad: "Intermedio" },
    { numero: 41, id: "insulating-heat-experiment", titulo: "Aislamiento térmico", dificultad: "Intermedio" },
    { numero: 42, id: "solar-panel-experiment", titulo: "Paneles solares", dificultad: "Intermedio" },
    { numero: 43, id: "ai-light-switch", titulo: "Interruptor de luz IA", dificultad: "Intermedio" },
    { numero: 44, id: "audible-cookie tin alarm", titulo: "Alarma sonora de galletas", dificultad: "Intermedio" },
    { numero: 45, id: "ai-social-distancing", titulo: "Distancia social IA", dificultad: "Intermedio" },
    { numero: 46, id: "ai-bird-box", titulo: "Caja de pájaros IA", dificultad: "Intermedio" },
    { numero: 47, id: "simple-data-logger", titulo: "Registrador de datos simple", dificultad: "Intermedio" }
  ],
  advanced: [
    { numero: 1, id: "proximity-beacon", titulo: "Baliza de proximidad", dificultad: "Avanzado" },
    { numero: 2, id: "guitar-1-touch-tunes", titulo: "Guitarra 1: Melodías", dificultad: "Avanzado" },
    { numero: 3, id: "guitar-2-chords", titulo: "Guitarra 2: Acordes", dificultad: "Avanzado" },
    { numero: 4, id: "guitar-3-octaves", titulo: "Guitarra 3: Octavas", dificultad: "Avanzado" },
    { numero: 5, id: "tilt-alarm", titulo: "Alarma de inclinación", dificultad: "Avanzado" },
    { numero: 6, id: "light-alarm", titulo: "Alarma de luz avanzada", dificultad: "Avanzado" },
    { numero: 7, id: "pressure-switch-alarm", titulo: "Interruptor de presión", dificultad: "Avanzado" },
    { numero: 8, id: "radio-door-alarm", titulo: "Alarma de puerta por radio", dificultad: "Avanzado" },
    { numero: 9, id: "pir-movement-alarm", titulo: "Alarma de movimiento PIR", dificultad: "Avanzado" },
    { numero: 10, id: "reaction-game", titulo: "Juego de reacción", dificultad: "Avanzado" },
    { numero: 11, id: "fireflies", titulo: "Luciérnagas", dificultad: "Avanzado" },
    { numero: 12, id: "max-min-temperature-logger", titulo: "Registrador Temp Máx-Mín", dificultad: "Avanzado" },
    { numero: 13, id: "energy-light-meter", titulo: "Medidor de luz de energía", dificultad: "Avanzado" },
    { numero: 14, id: "energy-light-timer", titulo: "Temporizador de luz de energía", dificultad: "Avanzado" },
    { numero: 15, id: "energy-cost-calculator", titulo: "Cálculo de coste de energía", dificultad: "Avanzado" },
    { numero: 16, id: "ai-sports-data-logger", titulo: "Datos deportivos con IA", dificultad: "Avanzado" },
    { numero: 17, id: "audible-teleporting-duck", titulo: "Pato teletransportador sonoro", dificultad: "Avanzado" },
    { numero: 18, id: "10-steps-counter", titulo: "Contador de 10 pasos", dificultad: "Avanzado" },
    { numero: 19, id: "audible-rock-paper-scissors", titulo: "Piedra, Papel o Tijera sonoro", dificultad: "Avanzado" }
  ]
};

export const MICROBIT_TUTORIALS = [];
