export const MICROBIT_CHALLENGES = {
  beginner: [
    {"numero": 1, "titulo": "Corazón", "id": "heart"},
    {"numero": 2, "titulo": "Corazón palpitante", "id": "beating-heart"},
    {"numero": 3, "titulo": "Animales animados", "id": "animated-animals"},
    {"numero": 4, "titulo": "Emoticonos", "id": "emojis"},
    {"numero": 5, "titulo": "Rastreador de emociones", "id": "emotion-badge"},
    {"numero": 6, "titulo": "Destello de sol", "id": "sunlight-sensor"},
    {"numero": 7, "titulo": "Luces nocturnas", "id": "night-light"},
    {"numero": 8, "titulo": "Brújula / Norte", "id": "compass-north"},
    {"numero": 9, "titulo": "Medidor de luz", "id": "light-meter"},
    {"numero": 10, "titulo": "Alarma de luz", "id": "light-alarm"},
    {"numero": 11, "titulo": "Termómetro", "id": "thermometer"},
    {"numero": 12, "titulo": "Alarma de temperatura", "id": "temperature-alarm"},
    {"numero": 13, "titulo": "Botón de pánico", "id": "panic-button"},
    {"numero": 14, "titulo": "Cara triste / Cara alegre", "id": "sad-face-happy-face"},
    {"numero": 15, "titulo": "Cara parpadeante", "id": "blinking-face"},
    {"numero": 16, "titulo": "Medidor de pasos", "id": "step-counter"},
    {"numero": 17, "titulo": "Dados", "id": "dice"},
    {"numero": 18, "titulo": "Piedra, papel o tijera", "id": "rock-paper-scissors"},
    {"numero": 19, "titulo": "Lámpara de humor", "id": "mood-lamp"},
    {"numero": 20, "titulo": "Insignia de nombre", "id": "name-badge"},
    {"numero": 21, "titulo": "Destellador", "id": "flasher"},
    {"numero": 22, "titulo": "Luciérnaga", "id": "fireflies"},
    {"numero": 23, "titulo": "Metrónomo", "id": "metronome"},
    {"numero": 24, "titulo": "Luces de aplauso", "id": "clap-lights"},
    {"numero": 25, "titulo": "¿Por dónde ahora?", "id": "which-way-now"},
    {"numero": 26, "titulo": "Registro de aves", "id": "bird-spotting-counter"},
    {"numero": 27, "titulo": "Recordatorio de riego", "id": "plant-watering-reminder"},
    {"numero": 28, "titulo": "Sensor de tacto", "id": "touch-sensor"},
    {"numero": 29, "titulo": "Emoción de sonido", "id": "sound-emotion"},
    {"numero": 30, "titulo": "Juguete sensorial", "id": "sensory-toy"},
    {"numero": 31, "titulo": "Nieve al agitar", "id": "snow-flakes"},
    {"numero": 32, "titulo": "Melodía al agitar", "id": "melody-player"},
    {"numero": 33, "titulo": "Contador", "id": "counter"},
    {"numero": 34, "titulo": "Selector de actividades", "id": "activity-picker"},
    {"numero": 35, "titulo": "Alarma inclinación", "id": "simple-tilt-alarm"},
    {"numero": 36, "titulo": "LED relajantes", "id": "calm-leds"},
    {"numero": 37, "titulo": "Salvar tortugas", "id": "saving-sea-turtles"},
    {"numero": 38, "titulo": "Iluminar redes", "id": "lighting-up-fishing-nets"},
    {"numero": 39, "titulo": "Enviar una sonrisa", "id": "send-a-smile"},
    {"numero": 40, "titulo": "Seguimiento animal", "id": "animal-tracker"},
    {"numero": 41, "titulo": "Emoción táctil", "id": "touch-emotion-badge"},
    {"numero": 42, "titulo": "Aplauso de corazones", "id": "clapping-heart"},
    {"numero": 43, "titulo": "Luces de discoteca", "id": "disco-lights"},
    {"numero": 44, "titulo": "Medidor de sonido", "id": "sound-meter"},
    {"numero": 45, "titulo": "Corazón táctil", "id": "touch-heart"},
    {"numero": 46, "titulo": "Emoción sonido", "id": "sound-emotion-badge"},
    {"numero": 47, "titulo": "Contador especies", "id": "species-counter"},
    {"numero": 48, "titulo": "Alerta botella agua", "id": "water-bottle-alert"},
    {"numero": 49, "titulo": "Alarma galletas", "id": "cookie-jar-alarm"},
    {"numero": 50, "titulo": "¡Levántate!", "id": "get-up-and-go"},
    {"numero": 51, "titulo": "Probador de tablas", "id": "times-table-tester"}
  ],
  intermediate: [
    {"numero": 1, "titulo": "Patata caliente", "id": "hot-potato"},
    {"numero": 2, "titulo": "Caliente y frío", "id": "hot-and-cold"},
    {"numero": 3, "titulo": "Calculadora distancia", "id": "distance-calculator"},
    {"numero": 4, "titulo": "Cuéntame un secreto", "id": "tell-me-a-secret"},
    {"numero": 5, "titulo": "Termómetro int/ext", "id": "indoor-outdoor-thermometer"},
    {"numero": 6, "titulo": "Baliza latidos", "id": "heartbeat-beacon"},
    {"numero": 7, "titulo": "Búsqueda del tesoro", "id": "treasure-hunt"},
    {"numero": 8, "titulo": "Matriz actividades", "id": "activity-picker"},
    {"numero": 9, "titulo": "Termómetro Fahrenheit", "id": "fahrenheit-thermometer"},
    {"numero": 10, "titulo": "Gramola con volumen", "id": "volume-jukebox"},
    {"numero": 11, "titulo": "Alarma puerta", "id": "simple-door-alarm"},
    {"numero": 12, "titulo": "Temporizador táctil", "id": "touch-timer"},
    {"numero": 13, "titulo": "Cronómetro táctil", "id": "touch-stopwatch"},
    {"numero": 14, "titulo": "Registrador sonido", "id": "sound-logger"},
    {"numero": 15, "titulo": "Mascota micro:bit", "id": "microbit-pet"},
    {"numero": 16, "titulo": "Nivel de burbuja", "id": "bubble-level"},
    {"numero": 17, "titulo": "Brújula de sonido", "id": "sound-compass"},
    {"numero": 18, "titulo": "Vela", "id": "candle"},
    {"numero": 19, "titulo": "Cronómetro radio", "id": "radio-stopwatch"},
    {"numero": 20, "titulo": "Contador tráfico", "id": "traffic-counter"},
    {"numero": 21, "titulo": "Riego de plantas", "id": "plant-watering-tracker"},
    {"numero": 22, "titulo": "Generador frases", "id": "random-phrase-generator"},
    {"numero": 23, "titulo": "Pares e impares", "id": "odd-even-number-game"},
    {"numero": 24, "titulo": "Lavado de manos", "id": "hand-wash-timer"},
    {"numero": 25, "titulo": "Experimento luz", "id": "light-experiment"},
    {"numero": 26, "titulo": "Circuito humano", "id": "human-circuit-experiment"},
    {"numero": 27, "titulo": "Volumen sonido", "id": "sound-volume-experiment"},
    {"numero": 28, "titulo": "Temp. máx/mín", "id": "max-min-thermometer"},
    {"numero": 29, "titulo": "Registrador temp.", "id": "temperature-logger"},
    {"numero": 30, "titulo": "Casa inteligente", "id": "smart-home-lights"},
    {"numero": 31, "titulo": "Luces aplauso IA", "id": "clap-lights-ai"},
    {"numero": 32, "titulo": "Alarma galletas v2", "id": "cookie-jar-alarm"}
  ],
  advanced: [
    {"numero": 1, "titulo": "Sensor proximidad", "id": "proximity-beacon"},
    {"numero": 2, "titulo": "Guitarra 1 - Melodías", "id": "guitar-1-touch-tunes"},
    {"numero": 3, "titulo": "Guitarra 2 - Acordes", "id": "guitar-2-chords"},
    {"numero": 4, "titulo": "Guitarra 3 - Octavas", "id": "guitar-3-octaves"},
    {"numero": 5, "titulo": "Alarma inclinación", "id": "tilt-alarm"},
    {"numero": 6, "titulo": "Alarma de luz", "id": "light-alarm"},
    {"numero": 7, "titulo": "Alarma presostato", "id": "pressure-switch-alarm"},
    {"numero": 8, "titulo": "Alarma inalámbrica", "id": "wireless-door-alarm"},
    {"numero": 9, "titulo": "Alarma PIR", "id": "pir-movement-alarm"},
    {"numero": 10, "titulo": "Juego reacción", "id": "reaction-game"},
    {"numero": 11, "titulo": "Datalogger MakeCode", "id": "makecode-data-logger"},
    {"numero": 12, "titulo": "Luciérnagas", "id": "fireflies"},
    {"numero": 13, "titulo": "Piedra Papel Tijera Sonido", "id": "rock-paper-scissors-with-sound"},
    {"numero": 14, "titulo": "Pitcher and catcher", "id": "pitcher-and-catcher"},
    {"numero": 15, "titulo": "Datalogger ambiental", "id": "environment-data-logger"},
    {"numero": 16, "titulo": "Datalogger radio", "id": "radio-data-logger"}
  ]
};
