export const MICROBIT_CHALLENGES = {
  beginner: [
    {"numero": 1, "titulo": "Corazón", "id": "heart"},
    {"numero": 2, "titulo": "Corazón palpitante", "id": "beating-heart"},
    {"numero": 3, "titulo": "Animales animados", "id": "animated-animals"},
    {"numero": 4, "titulo": "Insignia de emoción", "id": "emotion-badge"},
    {"numero": 5, "titulo": "Haz el tonto", "id": "giggling-emojis"},
    {"numero": 6, "titulo": "Expresar emociones usando flash", "id": "expressing-emotions-using-flash"},
    {"numero": 7, "titulo": "Aquí llega el sol", "id": "here-comes-the-sun"},
    {"numero": 8, "titulo": "Sol radiante", "id": "shining-sunbeams"},
    {"numero": 9, "titulo": "Sensor de luz solar", "id": "sunlight-sensor"},
    {"numero": 10, "titulo": "Insignia de identificación", "id": "name-badge"},
    {"numero": 11, "titulo": "Dado", "id": "dice"},
    {"numero": 12, "titulo": "Bola 8 mágica", "id": "magic-8-ball"},
    {"numero": 13, "titulo": "Piedra, papel o tijera", "id": "rock-paper-scissors"},
    {"numero": 14, "titulo": "Dados gráficos", "id": "dice-graphic"},
    {"numero": 15, "titulo": "Contador de pasos", "id": "step-counter"},
    {"numero": 16, "titulo": "Brújula", "id": "compass"},
    {"numero": 17, "titulo": "Termómetro", "id": "thermometer"},
    {"numero": 18, "titulo": "Alarma de luz", "id": "light-alarm"},
    {"numero": 19, "titulo": "Despertador de sol", "id": "sunrise-alarm"},
    {"numero": 20, "titulo": "Sensor de sonidos", "id": "sound-sensor"},
    {"numero": 21, "titulo": "Aplausómetro", "id": "clap-o-meter"},
    {"numero": 22, "titulo": "Luciérnagas", "id": "fireflies"},
    {"numero": 23, "titulo": "Luciérnagas sincronizadas", "id": "synchronized-fireflies"},
    {"numero": 24, "titulo": "Luces nocturnas", "id": "night-light"},
    {"numero": 25, "titulo": "Árbol de navidad", "id": "christmas-tree"},
    {"numero": 26, "titulo": "Árbol de navidad animado", "id": "animated-christmas-tree"},
    {"numero": 27, "titulo": "Luces de navidad", "id": "christmas-lights"},
    {"numero": 28, "titulo": "Decoración festiva", "id": "festive-decoration"},
    {"numero": 29, "titulo": "Exploración ambiental", "id": "environmental-exploration"},
    {"numero": 30, "titulo": "Pasos de baile", "id": "dance-steps"},
    {"numero": 31, "titulo": "Bola de nieve", "id": "snow-globe"},
    {"numero": 32, "titulo": "Agitar y sonidos", "id": "shake-and-sounds"},
    {"numero": 33, "titulo": "Insignia de emoción audible", "id": "audible-emotion-badge"},
    {"numero": 34, "titulo": "Pato teletransportador", "id": "teleporting-duck"},
    {"numero": 35, "titulo": "Hilo musical", "id": "jukebox"},
    {"numero": 36, "titulo": "Selector de actividades", "id": "activity-picker"},
    {"numero": 37, "titulo": "Alarma de inclinación simple", "id": "simple-tilt-alarm"},
    {"numero": 38, "titulo": "Contador", "id": "counter"},
    {"numero": 39, "titulo": "Piano táctil", "id": "touch-tone-piano"},
    {"numero": 40, "titulo": "Gato Scratch", "id": "scratch-cat"},
    {"numero": 41, "titulo": "Instrumento Scratch", "id": "scratch-instrument"},
    {"numero": 42, "titulo": "Joy-pad Scratch", "id": "scratch-joy-pad"},
    {"numero": 43, "titulo": "Metrónomo", "id": "metronome"},
    {"numero": 44, "titulo": "Luces de aplauso", "id": "clap-lights"},
    {"numero": 45, "titulo": "¿Por dónde ahora?", "id": "which-way-now"},
    {"numero": 46, "titulo": "Contador de especies", "id": "species-counter"},
    {"numero": 47, "titulo": "Alerta de botella de agua", "id": "water-bottle-alert"},
    {"numero": 48, "titulo": "Alarma de lata de galletas", "id": "cookie-tin-alarm"},
    {"numero": 49, "titulo": "Saludos al azar", "id": "random-greetings"},
    {"numero": 50, "titulo": "Tablas de multiplicar", "id": "times-tables-test"},
    {"numero": 51, "titulo": "Juego del pato", "id": "duck-game"}
  ],
  "intermediate": [
    {"numero": 1, "titulo": "Luz ambiental", "id": "mood-light"},
    {"numero": 2, "titulo": "Insignia", "id": "badge"},
    {"numero": 3, "titulo": "Cara triste", "id": "sad-face"},
    {"numero": 4, "titulo": "Botón de ánimo", "id": "cheering-up-button"},
    {"numero": 5, "titulo": "Lanzamiento de moneda", "id": "coin-toss"},
    {"numero": 6, "titulo": "Cara feliz", "id": "happy-face"},
    {"numero": 7, "titulo": "Batido de sentimientos", "id": "feeling-shake"},
    {"numero": 8, "titulo": "Termómetro Fahrenheit", "id": "fahrenheit-thermometer"},
    {"numero": 9, "titulo": "Alarma de puerta simple", "id": "simple-door-alarm"},
    {"numero": 10, "titulo": "Temporizador táctil", "id": "touch-timer"},
    {"numero": 11, "titulo": "Búsqueda del tesoro por radio", "id": "radio-scavenger-hunt"},
    {"numero": 12, "titulo": "Alarma contra intrusos por radio", "id": "radio-intruder-alarm"},
    {"numero": 13, "titulo": "Sensor de temperatura remoto", "id": "remote-temperature-sensor"},
    {"numero": 14, "titulo": "Datalogger de luz", "id": "light-logger"},
    {"numero": 15, "titulo": "Datalogger de humedad del suelo", "id": "soil-moisture-logger"},
    {"numero": 16, "titulo": "Alarma de puerta inalámbrica", "id": "wireless-door-alarm"},
    {"numero": 17, "titulo": "Radiomedidor de ánimo", "id": "radio-mood-o-meter"},
    {"numero": 18, "titulo": "Pato teletransportador por radio", "id": "radio-teleporting-duck"},
    {"numero": 19, "titulo": "Luciérnagas por radio", "id": "radio-fireflies"},
    {"numero": 20, "titulo": "Rasgos animales por radio", "id": "radio-animal-traits"},
    {"numero": 21, "titulo": "Búsqueda del tesoro", "id": "treasure-hunt"},
    {"numero": 22, "titulo": "Matriz de actividades", "id": "activity-array"},
    {"numero": 23, "titulo": "Hilo musical con volumen", "id": "jukebox-with-volume"},
    {"numero": 24, "titulo": "Botón de ánimo por radio", "id": "radio-cheering-up-button"},
    {"numero": 25, "titulo": "Lanzador de huevos", "id": "egg-toss"},
    {"numero": 26, "titulo": "Juego de aplausos", "id": "clap-game"},
    {"numero": 27, "titulo": "Luces de aplauso con IA", "id": "clap-lights-ai"},
    {"numero": 28, "titulo": "Alarma sonora de la caja de galletas", "id": "cookie-tin-alarm-sound"},
    {"numero": 29, "titulo": "Búsqueda de flora y fauna", "id": "flora-and-fauna-search"},
    {"numero": 30, "titulo": "Sensor de temperatura ambiente", "id": "ambient-temperature-sensor"},
    {"numero": 31, "titulo": "Medidor de luz solar", "id": "sunlight-meter"},
    {"numero": 32, "titulo": "Temporizador de luz solar", "id": "sunlight-timer"},
    {"numero": 33, "titulo": "Calculadora de costes energéticos", "id": "energy-cost-calculator"},
    {"numero": 34, "titulo": "Registrador de datos deportivos con IA", "id": "ai-sports-data-logger"},
    {"numero": 35, "titulo": "Alarma de inclinación inalámbrica", "id": "wireless-tilt-alarm"},
    {"numero": 36, "titulo": "Contador de pasos inalámbrico", "id": "wireless-step-counter"},
    {"numero": 37, "titulo": "Brújula de calor", "id": "heat-compass"},
    {"numero": 38, "titulo": "Búsqueda de objetos inalámbrica", "id": "wireless-object-finder"},
    {"numero": 39, "titulo": "Estación meteorológica inalámbrica", "id": "wireless-weather-station"},
    {"numero": 40, "titulo": "Termómetro inalámbrico", "id": "wireless-thermometer"},
    {"numero": 41, "titulo": "Sensor de humedad inalámbrico", "id": "wireless-moisture-sensor"},
    {"numero": 42, "titulo": "Alerta de intruso inalámbrica", "id": "wireless-intruder-alert"},
    {"numero": 43, "titulo": "Sensor de luz inalámbrico", "id": "wireless-light-sensor"},
    {"numero": 44, "titulo": "Sensor de sonido inalámbrico", "id": "wireless-sound-sensor"},
    {"numero": 45, "titulo": "Medidor de pasos inalámbrico", "id": "wireless-pedometer"},
    {"numero": 46, "titulo": "Contador de radio", "id": "radio-counter"}
  ],
  "advanced": [
    {"numero": 1, "titulo": "Medidor de energía de luz", "id": "energy-light-meter"},
    {"numero": 2, "titulo": "Temporizador de energía de luz", "id": "energy-light-timer"},
    {"numero": 3, "titulo": "Calculadora de costes energéticos", "id": "energy-cost-calculator"},
    {"numero": 4, "titulo": "Registrador de datos deportivos con IA", "id": "ai-sports-data-logger"},
    {"numero": 5, "titulo": "Pato teletransportable audible", "id": "audible-teleporting-duck"},
    {"numero": 6, "titulo": "Contador de 10 pasos", "id": "10-steps-counter"},
    {"numero": 7, "titulo": "Piedra, papel o tijera audible", "id": "audible-rock-paper-scissors"},
    {"numero": 8, "titulo": "Brújula analógica", "id": "analog-compass"},
    {"numero": 9, "titulo": "Guitarra por radio", "id": "radio-guitar"},
    {"numero": 10, "titulo": "Guitarra con acordes", "id": "guitar-with-chords"},
    {"numero": 11, "titulo": "Teclado de frutas por radio", "id": "radio-fruit-keyboard"},
    {"numero": 12, "titulo": "Piano por radio", "id": "radio-piano"},
    {"numero": 13, "titulo": "Hilo musical por radio", "id": "radio-jukebox"},
    {"numero": 14, "titulo": "Alarma antirrobo remota", "id": "remote-burglar-alarm"},
    {"numero": 15, "titulo": "Alarma de seguridad por radio", "id": "radio-security-alarm"},
    {"numero": 16, "titulo": "Sensor inalámbrico con registro de datos", "id": "wireless-sensor-with-datalogging"},
    {"numero": 17, "titulo": "Datalogger inalámbrico", "id": "wireless-data-logger"},
    {"numero": 18, "titulo": "Contador de tráfico con IA", "id": "ai-traffic-counter"},
    {"numero": 19, "titulo": "Control por gestos con IA", "id": "ai-gesture-control"},
    {"numero": 20, "titulo": "Control por emociones con IA", "id": "ai-emotion-control"},
    {"numero": 21, "titulo": "Casa inteligente con IA", "id": "ai-smart-home"},
    {"numero": 22, "titulo": "Monitor ambiental con IA", "id": "ai-environmental-monitor"},
    {"numero": 23, "titulo": "Monitor de plantas con IA", "id": "ai-plant-monitor"},
    {"numero": 24, "titulo": "Monitor de animales con IA", "id": "ai-animal-monitor"},
    {"numero": 25, "titulo": "Cámara de seguridad con IA", "id": "ai-security-camera"},
    {"numero": 26, "titulo": "Monitor de fitness con IA", "id": "ai-fitness-tracker"},
    {"numero": 27, "titulo": "Juego de reacción", "id": "reaction-game"},
    {"numero": 28, "titulo": "Luciérnagas", "id": "fireflies"}
  ]
};
