// Raspberry Pi Scratch Challenges - Updated 2026
// Basado en el currículo oficial de Raspberry Pi Projects (Scratch)

export const RASPBERRY_SCRATCH_L1 = [
  { numero: 1, id: "archery", titulo: "Tiro con arco", dificultad: "Principiante" },
  { numero: 2, id: "astronaut-reaction-times", titulo: "Tiempo de reacción espacial", dificultad: "Principiante" },
  { numero: 3, id: "balloons", titulo: "Globos", dificultad: "Principiante" },
  { numero: 4, id: "beat-the-goalie", titulo: "Para el penalti", dificultad: "Principiante" },
  { numero: 5, id: "binary-hero", titulo: "Héroe binario", dificultad: "Principiante" },
  { numero: 6, id: "boat-race", titulo: "Carrera de barcos", dificultad: "Principiante" },
  { numero: 7, id: "broadcasting-spells", titulo: "Hechizos de transmisión", dificultad: "Principiante" },
  { numero: 8, id: "butterfly-garden", titulo: "Jardín de mariposas", dificultad: "Principiante" },
  { numero: 9, id: "catch-the-bus", titulo: "Atrapa el autobús", dificultad: "Principiante" },
  { numero: 10, id: "catch-the-dots", titulo: "Atrapa los puntos", dificultad: "Principiante" },
  { numero: 11, id: "cats", titulo: "¡GATOS!", dificultad: "Principiante" },
  { numero: 12, id: "chatbot", titulo: "Chatbot", dificultad: "Principiante" },
  { numero: 13, id: "clone-wars", titulo: "Guerras de clones", dificultad: "Principiante" },
  { numero: 14, id: "count-the-creatures", titulo: "Cuenta las criaturas", dificultad: "Principiante" },
  { numero: 15, id: "cricket", titulo: "Cricket", dificultad: "Principiante" },
  { numero: 16, id: "drum-star", titulo: "Estrella de la batería", dificultad: "Principiante" },
  { numero: 17, id: "find-the-bug", titulo: "Busca el error", dificultad: "Principiante" },
  { numero: 18, id: "from-me-to-you", titulo: "De mí para ti", dificultad: "Principiante" },
  { numero: 19, id: "ghostbusters", titulo: "Cazafantasmas", dificultad: "Principiante" },
  { numero: 20, id: "green-goals", titulo: "Goles verdes", dificultad: "Principiante" },
  { numero: 21, id: "grow-a-tree", titulo: "Planta un árbol", dificultad: "Principiante" },
  { numero: 22, id: "how-are-you", titulo: "¿Cómo estás?", dificultad: "Principiante" },
  { numero: 23, id: "jazzy-jumpers", titulo: "Saltadores de jazz", dificultad: "Principiante" },
  { numero: 24, id: "jukskei", titulo: "Jukskei", dificultad: "Principiante" },
  { numero: 25, id: "kabaddi", titulo: "¡Kabaddi!", dificultad: "Principiante" },
  { numero: 26, id: "kit-chooser", titulo: "Selector de equipación", dificultad: "Principiante" },
  { numero: 27, id: "lost-in-space", titulo: "Perdidos en el espacio", dificultad: "Principiante" },
  { numero: 28, id: "scratchpc-musical-instrument", titulo: "Instrumento musical", dificultad: "Principiante" },
  { numero: 29, id: "scratchpc-interactive-book", titulo: "Libro interactivo", dificultad: "Principiante" },
  { numero: 30, id: "memory", titulo: "Memoria", dificultad: "Principiante" },
  { numero: 31, id: "olympic-rings", titulo: "Anillos olímpicos", dificultad: "Principiante" },
  { numero: 32, id: "paint-box", titulo: "Caja de lápices", dificultad: "Principiante" },
  { numero: 33, id: "party-pinata", titulo: "Piñata de fiesta", dificultad: "Principiante" },
  { numero: 34, id: "physical-computing-with-scratch", titulo: "Computación física", dificultad: "Principiante" },
  { numero: 35, id: "relax-stretch", titulo: "Relájate y estira", dificultad: "Principiante" },
  { numero: 36, id: "rock-band", titulo: "Banda de rock", dificultad: "Principiante" },
  { numero: 37, id: "santa-detector", titulo: "Detector de Papá Noel", dificultad: "Principiante" },
  { numero: 38, id: "scary-spot-the-difference-scratch", titulo: "Encuentra las diferencias", dificultad: "Principiante" },
  { numero: 39, id: "scratch-cat-goes-skiing", titulo: "Gato esquiador", dificultad: "Principiante" },
  { numero: 40, id: "scratch-led-game", titulo: "Juego LED", dificultad: "Principiante" },
  { numero: 41, id: "silly-eyes", titulo: "Ojos locos", dificultad: "Principiante" },
  { numero: 42, id: "space-talk", titulo: "Charla espacial", dificultad: "Principiante" },
  { numero: 43, id: "sprint", titulo: "¡Sprint!", dificultad: "Principiante" },
  { numero: 44, id: "stress-ball", titulo: "Bola antiestrés", dificultad: "Principiante" },
  { numero: 45, id: "sunset", titulo: "Atardecer", dificultad: "Principiante" },
  { numero: 46, id: "surprise-animation", titulo: "Animación sorpresa", dificultad: "Principiante" },
  { numero: 47, id: "flatgame", titulo: "Mundo plano", dificultad: "Principiante" },
  { numero: 48, id: "turtle-tracker", titulo: "Rastreador de tortugas", dificultad: "Principiante" },
  { numero: 49, id: "rpi-wire-loop-game-scratch", titulo: "Juego del alambre", dificultad: "Principiante" },
  { numero: 50, id: "world-environment-day", titulo: "Día del Medio Ambiente", dificultad: "Principiante" },
  { numero: 51, id: "alien-language", titulo: "Lenguaje alienígena", dificultad: "Principiante" },
  { numero: 52, id: "chomp-the-cheese", titulo: "Come el queso", dificultad: "Principiante" },
  { numero: 53, id: "doodle-detector", titulo: "Detector de garabatos", dificultad: "Principiante" }
];

export const RASPBERRY_SCRATCH_L2 = [
  { numero: 1, id: "scratch-3d-science", titulo: "Pantalla científica 3D", dificultad: "Intermedio" },
  { numero: 2, id: "poetry-generator", titulo: "Generador de poesía", dificultad: "Intermedio" },
  { numero: 3, id: "dodgeball", titulo: "Balón prisionero", dificultad: "Intermedio" },
  { numero: 4, id: "dont-fall-in", titulo: "¡No te caigas!", dificultad: "Intermedio" },
  { numero: 5, id: "flappy-parrot", titulo: "Loro volador", dificultad: "Intermedio" },
  { numero: 6, id: "flower-generator", titulo: "Generador de flores", dificultad: "Intermedio" },
  { numero: 7, id: "focus-on-the-prize", titulo: "Concéntrate en el premio", dificultad: "Intermedio" },
  { numero: 8, id: "fruit-salad", titulo: "Ensalada de frutas", dificultad: "Intermedio" },
  { numero: 9, id: "grow-a-dragonfly", titulo: "Cría una libélula", dificultad: "Intermedio" },
  { numero: 10, id: "i-made-you-a-book", titulo: "Te hice un libro", dificultad: "Intermedio" },
  { numero: 11, id: "nature-rover", titulo: "Rover de la naturaleza", dificultad: "Intermedio" },
  { numero: 12, id: "next-customer-please", titulo: "Siguiente cliente, por favor", dificultad: "Intermedio" },
  { numero: 13, id: "puzzle-room", titulo: "Sala de rompecabezas", dificultad: "Intermedio" },
  { numero: 14, id: "rpi-stress-buster-with-scratch", titulo: "Antiestrés con Raspberry Pi", dificultad: "Intermedio" },
  { numero: 15, id: "save-the-shark", titulo: "Salva al tiburón", dificultad: "Intermedio" },
  { numero: 16, id: "serene-scene", titulo: "Escena serena", dificultad: "Intermedio" },
  { numero: 17, id: "snowball-fight", titulo: "Pelea de bolas de nieve", dificultad: "Intermedio" },
  { numero: 18, id: "synchronised-swimming", titulo: "Natación sincronizada", dificultad: "Intermedio" },
  { numero: 19, id: "tree-life-simulator", titulo: "Simulador de vida de árbol", dificultad: "Intermedio" },
  { numero: 20, id: "username-generator", titulo: "Generador de nombres de usuario", dificultad: "Intermedio" },
  { numero: 21, id: "did-you-like-it", titulo: "¿Te gustó?", dificultad: "Intermedio" }
];

export const RASPBERRY_SCRATCH_CHALLENGES = [
  { numero: 1, id: "brain-game", titulo: "Juego mental", dificultad: "Avanzado" },
  { numero: 2, id: "create-your-own-world", titulo: "Crea tu propio mundo", dificultad: "Avanzado" },
  { numero: 3, id: "guess-the-flag", titulo: "Adivina la bandera", dificultad: "Avanzado" },
  { numero: 4, id: "lineup", titulo: "Pónganse en fila", dificultad: "Avanzado" },
  { numero: 5, id: "mandala", titulo: "Mandala", dificultad: "Avanzado" },
  { numero: 6, id: "music-maker", titulo: "Fabricante de música", dificultad: "Avanzado" },
  { numero: 7, id: "swarms-schools-flocks", titulo: "Enjambres, cardúmenes y bandadas", dificultad: "Avanzado" },
  { numero: 8, id: "this-sprite-needs-you", titulo: "Este duende te necesita", dificultad: "Avanzado" },
  { numero: 9, id: "welcome-to-my-world", titulo: "Bienvenido a mi mundo", dificultad: "Avanzado" }
];
