export const RASPBERRY_SCRATCH_L1 = [
  { numero: 1, id: "catch-the-dots", titulo: "Atrapa los Puntos", dificultad: "Iniciación", explicacion: "Haz un juego de atrapar puntos.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/catch-the-dots" },
  { numero: 2, id: "rock-band", titulo: "Banda de Rock", dificultad: "Iniciación", explicacion: "Aprende cómo codificar tus propios instrumentos musicales.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/rock-band" },
  { numero: 3, id: "boat-race", titulo: "Carrera de Barcos", dificultad: "Iniciación", explicacion: "Haz un juego de carreras de barcos en el que tendrás que evitar obstáculos.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/boat-race" },
  { numero: 4, id: "ghostbusters", titulo: "Cazafantasmas", dificultad: "Iniciación", explicacion: "¡Haz un juego sobre atrapar fantasmas!", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/ghostbusters" },
  { numero: 5, id: "chatbot", titulo: "Chatbot", dificultad: "Iniciación", explicacion: "¡Aprende a programar tu propio robot que habla!", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/chatbot" },
  { numero: 6, id: "cats", titulo: "¡GATOS!", dificultad: "Iniciación", explicacion: "Crea un juego en el que guíes a los gatos a un lugar seguro.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/cats" },
  { numero: 7, id: "balloons", titulo: "Globos", dificultad: "Iniciación", explicacion: "¡Aprende a hacer un juego de reventar globos!", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/balloons" },
  { numero: 8, id: "clone-wars", titulo: "Guerras de Clones", dificultad: "Iniciación", explicacion: "Crea un juego en el que cual tengas que salvar la Tierra.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/clone-wars" },
  { numero: 9, id: "archery", titulo: "Tiro con arco", dificultad: "Iniciación", explicacion: "Dispara flechas tan cerca del blanco de la diana como puedas.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/archery" },
  { numero: 10, id: "astronaut-reaction-times", titulo: "Astronaut Reaction Time Game", dificultad: "Iniciación", explicacion: "¿Tienes los reflejos rápidos necesarios para ser astronauta?", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/astronaut-reaction-times" },
  { numero: 11, id: "beat-the-goalie", titulo: "Beat the Goalie", dificultad: "Iniciación", explicacion: "Crea un juego de fútbol en el que tienes que marcar tantos goles como puedas.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/beat-the-goalie" },
  { numero: 12, id: "burping-monster", titulo: "Burping Monster", dificultad: "Iniciación", explicacion: "Crea un monstruo que eructa cuando se hace clic en él.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/burping-monster" },
  { numero: 13, id: "casting-spells", titulo: "Casting Spells", dificultad: "Iniciación", explicacion: "Usa una varita mágica para elegir hechizos.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/casting-spells" },
  { numero: 14, id: "catch-the-bus", titulo: "Catch the bus", dificultad: "Iniciación", explicacion: "Codifica personajes para que caminen o vuelen hacia el autobús.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/catch-the-bus" },
  { numero: 15, id: "count-the-creatures", titulo: "Count the creatures", dificultad: "Iniciación", explicacion: "Crea una cámara de vida silvestre.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/count-the-creatures" },
  { numero: 16, id: "dance-party", titulo: "Dance Party", dificultad: "Iniciación", explicacion: "¡Haz que una persona baile al ritmo de la música!", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/dance-party" },
  { numero: 17, id: "deep-sea-cleanup", titulo: "Deep Sea Cleanup", dificultad: "Iniciación", explicacion: "Ayuda al submarino a limpiar el mar.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/deep-sea-cleanup" },
  { numero: 18, id: "dodgeball-l1", titulo: "Dodgeball L1", dificultad: "Iniciación", explicacion: "Crea un juego en el que esquivas la pelota.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/dodgeball" },
  { numero: 19, id: "find-the-bug", titulo: "Find the bug", dificultad: "Iniciación", explicacion: "Encuentra el bicho escondido en cada nivel.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/find-the-bug" },
  { numero: 20, id: "from-me-to-you", titulo: "From me to you", dificultad: "Iniciación", explicacion: "Crea tu propia tarjeta digital interactiva.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/from-me-to-you" },
  { numero: 21, id: "give-a-shout-out", titulo: "Give a shout out", dificultad: "Iniciación", explicacion: "Haz un proyecto para ayudar a alguien.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/give-a-shout-out" },
  { numero: 22, id: "go-karting", titulo: "Go-karting", dificultad: "Iniciación", explicacion: "Crea un juego de carreras para dos jugadores.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/go-karting" },
  { numero: 23, id: "greet-the-earth", titulo: "Greet the Earth", dificultad: "Iniciación", explicacion: "Crea un proyecto sencillo de Scratch.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/greet-the-earth" },
  { numero: 24, id: "grow-a-tree", titulo: "Grow a tree", dificultad: "Iniciación", explicacion: "Crea un jardín digital.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/grow-a-tree" },
  { numero: 25, id: "how-are-you", titulo: "How are you?", dificultad: "Iniciación", explicacion: "Pregúntale a alguien cómo está.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/how-are-you" },
  { numero: 26, id: "jazzy-jumpers", titulo: "Jazzy jumpers", dificultad: "Iniciación", explicacion: "Crea un juego de memoria.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/jazzy-jumpers" },
  { numero: 27, id: "jukskei", titulo: "Jukskei", dificultad: "Iniciación", explicacion: "Construye tu propio juego de jukskei.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/jukskei" },
  { numero: 28, id: "kabaddi", titulo: "Kabaddi!", dificultad: "Iniciación", explicacion: "Haz un juego inspirado en el kabaddi.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/kabaddi" },
  { numero: 29, id: "lost-in-space", titulo: "Lost in Space", dificultad: "Iniciación", explicacion: "Aprende a programar tu propia animación.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/lost-in-space" },
  { numero: 30, id: "make-it-fly", titulo: "Make it fly", dificultad: "Iniciación", explicacion: "Crea una animación de vuelo.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/make-it-fly" },
  { numero: 31, id: "mystery-cave", titulo: "Mystery cave", dificultad: "Iniciación", explicacion: "Aprende a crear una misteriosa cueva espeluznante.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/mystery-cave" },
  { numero: 32, id: "paint-box", titulo: "Paint Box", dificultad: "Iniciación", explicacion: "Aprende a crear tu propio programa de dibujo.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/paint-box" },
  { numero: 33, id: "party-pinata", titulo: "Party piñata", dificultad: "Iniciación", explicacion: "Crea una piñata que se balancea.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/party-pinata" },
  { numero: 34, id: "scratchpc-interactive-book", titulo: "Make an interactive book", dificultad: "Iniciación", explicacion: "Crea un libro interactivo.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/scratchpc-interactive-book" },
  { numero: 35, id: "planet-and-star", titulo: "Planet and star", dificultad: "Iniciación", explicacion: "Crea una animación planetaria.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/planet-and-star" },
  { numero: 36, id: "protect-the-planet", titulo: "Protect the planet", dificultad: "Iniciación", explicacion: "Construye un juego para proteger el planeta.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/protect-the-planet" },
  { numero: 37, id: "red-light-green-light", titulo: "Red light, green light", dificultad: "Iniciación", explicacion: "Crea un juego sencillo de reacción.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/red-light-green-light" },
  { numero: 38, id: "relaxing-scene", titulo: "Relaxing scene", dificultad: "Iniciación", explicacion: "Crea una escena relajante.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/relaxing-scene" },
  { numero: 39, id: "santa-detector", titulo: "Santa detector", dificultad: "Iniciación", explicacion: "Crea una alarma para detectar a Santa.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/santa-detector" },
  { numero: 40, id: "scary-spot-the-difference-scratch", titulo: "Scary 'spot the difference'", dificultad: "Iniciación", explicacion: "Haz un juego de encontrar diferencias con susto.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/scary-spot-the-difference-scratch" },
  { numero: 41, id: "skiing", titulo: "Skiing", dificultad: "Iniciación", explicacion: "Crea un juego de esquí.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/skiing" },
  { numero: 42, id: "snail-race", titulo: "Snail race", dificultad: "Iniciación", explicacion: "Construye un juego de carreras de caracoles.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/snail-race" },
  { numero: 43, id: "space-junk", titulo: "Space Junk", dificultad: "Iniciación", explicacion: "Protege la estación espacial.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/space-junk" },
  { numero: 44, id: "sparkle-help", titulo: "Sparkle help", dificultad: "Iniciación", explicacion: "Ayuda al alienígena Sparkle.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/sparkle-help" },
  { numero: 45, id: "stress-ball", titulo: "Stress ball", dificultad: "Iniciación", explicacion: "Crea una pelota antiestrés que puedas aplasher.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/stress-ball" },
  { numero: 46, id: "sunset", titulo: "Sunset", dificultad: "Iniciación", explicacion: "¡Mira el amanecer y el atardecer en ciudades de todo el mundo!", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/sunset" },
  { numero: 47, id: "synchronised-swimming", titulo: "Synchronised swimming", dificultad: "Iniciación", explicacion: "Crea tus propias nadadoras sincronizadas.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/synchronised-swimming" },
  { numero: 48, id: "throw-the-fruit", titulo: "Throw the fruit", dificultad: "Iniciación", explicacion: "Construye un juego de lanzar fruta.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/throw-the-fruit" },
  { numero: 49, id: "to-the-moon", titulo: "To the moon", dificultad: "Iniciación", explicacion: "Programa un módulo de aterrizaje lunar.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/to-the-moon" },
  { numero: 50, id: "water-your-garden", titulo: "Water your garden", dificultad: "Iniciación", explicacion: "Crea un jardín interactivo.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/water-your-garden" },
  { numero: 51, id: "whats-that", titulo: "What's that?", dificultad: "Iniciación", explicacion: "Crea un juego de adivinanzas.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/whats-that" },
  { numero: 52, id: "world-cup", titulo: "World Cup", dificultad: "Iniciación", explicacion: "Haz un juego de penaltis de la Copa del Mundo.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/world-cup" },
  { numero: 53, id: "yoga", titulo: "Yoga", dificultad: "Iniciación", explicacion: "Crea una animación de yoga.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/yoga" }
];

export const RASPBERRY_SCRATCH_L2 = [
  { numero: 1, id: "dodgeball-l2", titulo: "Esquiva-pelotas", dificultad: "Intermedio", explicacion: "Crea un juego de plataformas en el que tengas que esquivar pelotas.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/dodgeball" },
  { numero: 2, id: "poetry-generator", titulo: "Generador de poesía de Ada", dificultad: "Intermedio", explicacion: "¡Celebra el Ada Lovelace Day programando tu propio generador de poesía!", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/poetry-generator" },
  { numero: 3, id: "stunt-bike", titulo: "Carrera de obstáculos", dificultad: "Intermedio", explicacion: "Haz un juego de carreras de obstáculos.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/stunt-bike" },
  { numero: 4, id: "cat-and-mouse", titulo: "El gato y el ratón", dificultad: "Intermedio", explicacion: "Haz un juego de perseguir y atrapar.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/cat-and-mouse" },
  { numero: 5, id: "fruit-ninja", titulo: "Fruta Ninja", dificultad: "Intermedio", explicacion: "Corta la fruta con el puntero del ratón.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/fruit-ninja" },
  { numero: 6, id: "space-invaders", titulo: "Invasores del Espacio", dificultad: "Intermedio", explicacion: "¡Protege la Tierra de los invasores!", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/space-invaders" },
  { numero: 7, id: "maze", titulo: "Laberinto", dificultad: "Intermedio", explicacion: "Haz un juego de laberinto avanzado.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/maze" },
  { numero: 8, id: "think-of-a-number", titulo: "Pensar en un número", dificultad: "Intermedio", explicacion: "Haz un juego en el que el ordenador tenga que adivinar tu número.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/think-of-a-number" },
  { numero: 9, id: "scratch-3d-science", titulo: "3D LED science display", dificultad: "Intermedio", explicacion: "Crea una pantalla científica 3D.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/scratch-3d-science" },
  { numero: 10, id: "dont-fall-in", titulo: "Don't fall in!", dificultad: "Intermedio", explicacion: "Diseña un juego de obstáculos con vista aérea.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/dont-fall-in" },
  { numero: 11, id: "flower-field", titulo: "Flower field", dificultad: "Intermedio", explicacion: "Haz un programa que dibuje un campo de flores.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/flower-field" },
  { numero: 12, id: "forest-harmony", titulo: "Forest harmony", dificultad: "Intermedio", explicacion: "Crea una pieza de arte interactiva.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/forest-harmony" },
  { numero: 13, id: "line-of-best-fit", titulo: "Line of best fit", dificultad: "Intermedio", explicacion: "Crea un programa que trace datos.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/line-of-best-fit" },
  { numero: 14, id: "memory", titulo: "Memory", dificultad: "Intermedio", explicacion: "Crea un juego de memoria clásico.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/memory" },
  { numero: 15, id: "more-synchronised-swimming", titulo: "More synchronised swimming", dificultad: "Intermedio", explicacion: "Celebra las Olimpiadas con natación sincronizada.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/more-synchronised-swimming" },
  { numero: 16, id: "night-vision", titulo: "Night vision", dificultad: "Intermedio", explicacion: "Crea una cámara de visión nocturna virtual.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/night-vision" },
  { numero: 17, id: "flappy-parrot", titulo: "Flappy parrot", dificultad: "Intermedio", explicacion: "Guía a un loro a través de obstáculos móviles.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/flappy-parrot" },
  { numero: 18, id: "flower-generator", titulo: "Flower generator", dificultad: "Intermedio", explicacion: "Genera flores para crear fondos de pantalla o protectores.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/flower-generator" },
  { numero: 19, id: "magic-gift", titulo: "Magic gift", dificultad: "Intermedio", explicacion: "Crea un regalo mágico interactivo.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/magic-gift" },
  { numero: 20, id: "mega-fruit-salad", titulo: "Mega fruit salad", dificultad: "Intermedio", explicacion: "Crea un tazón gigante de ensalada de frutas.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/mega-fruit-salad" },
  { numero: 21, id: "on-the-hunt", titulo: "On the hunt", dificultad: "Intermedio", explicacion: "Crea un juego de búsqueda.", externalUrl: "https://projects.raspberrypi.org/es-ES/projects/on-the-hunt" }
];

export const RASPBERRY_SCRATCH_CHALLENGES = [
  {
    numero: 1,
    id: "create-your-own-world",
    titulo: "Crea tu propio mundo",
    dificultad: "Experto",
    explicacion: "Aprende a crear tu propio juego de aventura de mundo abierto.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/create-your-own-world",
    descripcion: "Diseña un mundo expansivo donde el jugador pueda explorar diferentes escenarios y recolectar objetos."
  },
  {
    numero: 2,
    id: "brain-game",
    titulo: "Juego mental",
    dificultad: "Experto",
    explicacion: "Aprende a crear un examen o juego de preguntas interactivo.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/brain-game",
    descripcion: "Crea un sistema de preguntas y respuestas que lleve la cuenta de la puntuación del jugador."
  },
  {
    numero: 3,
    id: "guess-the-flag",
    titulo: "Guess the flag",
    dificultad: "Experto",
    explicacion: "¡Crea un juego de adivinar banderas para ti y tus amigos!",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/guess-the-flag",
    descripcion: "Un juego de preguntas visual donde debes identificar países a partir de sus banderas."
  },
  {
    numero: 4,
    id: "lineup",
    titulo: "Line up",
    dificultad: "Experto",
    explicacion: "Crea un juego donde debes buscar a un personaje escondido en una multitud.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/lineup",
    descripcion: "Trabaja con clones y detección de ratón para crear un juego de búsqueda estilo '¿Dónde está Wally?'."
  },
  {
    numero: 5,
    id: "mandala",
    titulo: "Mandala",
    dificultad: "Experto",
    explicacion: "Crea mandalas generados por ordenador en Scratch.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/mandala",
    descripcion: "Utiliza la extensión de Lápiz para crear patrones geométricos complejos y coloridos."
  },
  {
    numero: 6,
    id: "music-maker",
    titulo: "Music maker",
    dificultad: "Experto",
    explicacion: "Diseña tu propio instrumento musical interactivo.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/music-maker",
    descripcion: "Combina sonidos, eventos de teclado y animaciones para crear una experiencia musical única."
  },
  {
    numero: 7,
    id: "swarms-schools-and-flocks",
    titulo: "Enjambres y bancos",
    dificultad: "Experto",
    explicacion: "Crea un juego que use clones para hacer enjambres, bancos de peces o bandadas de pájaros.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/swarms-schools-and-flocks",
    descripcion: "Aprende conceptos avanzados de movimiento de grupos usando clones en Scratch."
  },
  {
    numero: 8,
    id: "this-sprite-needs-you",
    titulo: "Este objeto te necesita",
    dificultad: "Experto",
    explicacion: "Crea una mascota virtual, un personaje o una simulación de la naturaleza.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/this-sprite-needs-you",
    descripcion: "Implementa sistemas de necesidades (hambre, energía) que el usuario deba gestionar interactuando con el objeto."
  },
  {
    numero: 9,
    id: "welcome-to-my-world",
    titulo: "Bienvenido a mi mundo",
    dificultad: "Experto",
    explicacion: "Construye un mundo 2.5D para explorar e interactuar.",
    externalUrl: "https://projects.raspberrypi.org/es-ES/projects/welcome-to-my-world",
    descripcion: "Crea una ilusión de profundidad usando capas y escalado de objetos para una exploración inmersiva."
  }
];
